2017-11-08T07:49:04 p2p:thread invoke for method load_configuration   load_configuration ] generating new private key for this node			node.cpp:4487
2017-11-08T07:49:05 p2p:thread invoke for method listen_to_p2p_network listen_to_p2p_networ ] listening for connections on endpoint 0.0.0.0:46520 (our first choice)			node.cpp:4604
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ] ----------------- PEER STATUS UPDATE --------------------			node.cpp:4741
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]  number of peers: 0 active, 26, 0 closing.  attempting to maintain 20 - 200 peers			node.cpp:4744
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 192.151.158.106:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 45.79.174.179:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 173.233.75.2:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 209.105.239.13:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 51.15.42.228:50696 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 51.15.61.160:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 148.251.80.54:4243 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 114.92.224.87:62015 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 139.162.183.240:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 45.77.136.107:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 212.47.249.84:50696 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 128.199.143.47:2015 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 104.236.144.84:1777 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 23.92.53.182:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 192.121.166.162:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 71.197.2.119:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 104.145.234.6:1777 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 84.200.84.162:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 149.56.17.159:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 108.61.176.106:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 188.241.58.128:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 45.32.117.94:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 81.89.101.133:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 94.130.15.169:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 45.32.159.93:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ]   handshaking peer 116.62.226.52:1776 in state ours(disconnected) theirs(disconnected)			node.cpp:4759
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ] --------- MEMORY USAGE ------------			node.cpp:4762
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ] node._active_sync_requests size: 0			node.cpp:4763
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ] node._received_sync_items size: 0			node.cpp:4764
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ] node._new_received_sync_items size: 0			node.cpp:4765
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ] node._items_to_fetch size: 0			node.cpp:4766
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ] node._new_inventory size: 0			node.cpp:4767
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ] node._message_cache size: 0			node.cpp:4768
2017-11-08T07:49:05 p2p:dump_node_status_task     dump_node_status ] --------- END MEMORY USAGE ------------			node.cpp:4778
2017-11-08T07:49:05   p2p:connect_to_task           connect_to ] fatal: error connecting to peer 51.15.61.160:1776: 0 exception: unspecified
Connection refused 
    {"message":"Connection refused"}
    asio  asio.cpp:60 error_handler			peer_connection.cpp:263
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task              destroy ] Unexpected exception from peer_connection's accept_or_connect_task : {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"error","file":"asio.cpp","line":60,"method":"error_handler","hostname":"","thread_name":"asio","timestamp":"2017-11-08T07:49:05"},"format":"${message} ","data":{"message":"Connection refused"}}]}			peer_connection.cpp:166
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05   p2p:connect_to_task           connect_to ] established outbound connection to 51.15.42.228:50696			peer_connection.cpp:259
2017-11-08T07:49:05 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"51.15.42.228","inbound_port":50696,"outbound_port":50696,"node_public_key":"03b14cb5c7368d0230014b6f5b6a0228c2cee4113178403076471aff4c0cbd8f23","signed_shared_secret":"205eeb9eab1bcfd5a1c33ade81a3327c0d6deb62bff90276156501809ec6e8c72d60915c8c6846c3fc37e17b1e094c077c720c384778f05ca36f16670b1d0d0587","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"43c0bd27292143ee8244fdef6fd1b6e1d9f12e546ef27cef8e174bb499470d37fb","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:05   p2p:connect_to_task           connect_to ] established outbound connection to 45.77.136.107:1776			peer_connection.cpp:259
2017-11-08T07:49:05 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"45.77.136.107","inbound_port":1776,"outbound_port":1776,"node_public_key":"0234f748b1c02c54205cd87a327efaf7903d2ed8d85fbdcc63831d25a6e4ed2d2f","signed_shared_secret":"1f5e0ecf4b1d00a558bc75d45898c2886bfa2866d089efc757412eb3d63ef08b51286727e8bacd8035119fe5e2778cd62e20f5bad624e7e9391ab873686e24ef02","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"8d2c3f204e1552bcedbd687eb269a16a8c68cc8fce68f214d90e39af49e162b872","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:05   p2p:connect_to_task           connect_to ] established outbound connection to 192.121.166.162:1776			peer_connection.cpp:259
2017-11-08T07:49:05   p2p:connect_to_task           connect_to ] established outbound connection to 84.200.84.162:1776			peer_connection.cpp:259
2017-11-08T07:49:05   p2p:connect_to_task           connect_to ] fatal: error connecting to peer 81.89.101.133:1776: 0 exception: unspecified
Connection refused 
    {"message":"Connection refused"}
    asio  asio.cpp:60 error_handler			peer_connection.cpp:263
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task              destroy ] Unexpected exception from peer_connection's accept_or_connect_task : {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"error","file":"asio.cpp","line":60,"method":"error_handler","hostname":"","thread_name":"asio","timestamp":"2017-11-08T07:49:05"},"format":"${message} ","data":{"message":"Connection refused"}}]}			peer_connection.cpp:166
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05   p2p:connect_to_task           connect_to ] established outbound connection to 148.251.80.54:4243			peer_connection.cpp:259
2017-11-08T07:49:05 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"192.121.166.162","inbound_port":1776,"outbound_port":1776,"node_public_key":"022d10653992817547534562c9adb7ab91dbeb078461fb59fb23a5eb95b758e56d","signed_shared_secret":"201fd370640bbc2657ab158832713312864bc6b9cbf059fa1409b660382c57eec7611548da26da395afff450e508d3e3befdb55c72ad9f195919f27935ee159fa6","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"91bcd57ec79bc75f9c9b8537408a4bfccbe53125fd754933701618cd6de8d8674a","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:05   p2p:connect_to_task           connect_to ] established outbound connection to 94.130.15.169:1776			peer_connection.cpp:259
2017-11-08T07:49:05 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"84.200.84.162","inbound_port":1776,"outbound_port":1776,"node_public_key":"03ba3c1bc553eed45104d9ad950a9c9772c12c3e22d375081e59c17d2f5ce98e57","signed_shared_secret":"1f1d64b1360d740fcbad7277e71cdb0b3d30659441c4af6e0c945e9bf888dfb24a0e9ad6f284ef095db26b98313cfa70cc0b1c2aeb9eeecf7df28defa9430a63a8","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"c3611922afc4388172f79e3d86361c1b253d79a8b00c4b21b296097f5449723e86","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:05   p2p:connect_to_task           connect_to ] established outbound connection to 108.61.176.106:1776			peer_connection.cpp:259
2017-11-08T07:49:05   p2p:connect_to_task           connect_to ] established outbound connection to 212.47.249.84:50696			peer_connection.cpp:259
2017-11-08T07:49:05   p2p:connect_to_task           connect_to ] established outbound connection to 139.162.183.240:1776			peer_connection.cpp:259
2017-11-08T07:49:05   p2p:connect_to_task           connect_to ] established outbound connection to 45.32.159.93:1776			peer_connection.cpp:259
2017-11-08T07:49:05 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"148.251.80.54","inbound_port":4243,"outbound_port":4243,"node_public_key":"02144ea8cf3032bb24fdd3c2a69fc273e4df96984452e9b077334b207204a31448","signed_shared_secret":"2066b97068ba849750a161599970f61eb4a83022a4080b462c70901f3fc6e0b8311e8ef01cb2c9a5fdc6e9ddd0ba6eade4ecb94c35d93ae3d7e77558d3571062d9","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"ca20da8ec268641e62f9264b4bcf2e9601b1a5b16eb6c8672a50c1845d57d8c840","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:05 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"94.130.15.169","inbound_port":1776,"outbound_port":1776,"node_public_key":"023d064db50ca1abc9f785cc61bfa46e7f55c62e707ca31f4d0aa2d5607cb3e077","signed_shared_secret":"201b77ca61fcac57576935da48babcf313e12ffbe6201e86eba7a678908eb224ea713b457b37eda975e5ffb760a9bb6461c658287ecb968a0c1c12949a0b2fbfed","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"f5c566e21099c97d02e38e6f639befecc1acac7e4de3712c39cfaad40fc928c52d","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:05 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"212.47.249.84","inbound_port":50696,"outbound_port":50696,"node_public_key":"034f2e5b12f51495da800c61e96dcb6e8450af051c22e0e1e9184164f59358ce98","signed_shared_secret":"200a7394691d795c66863c87cad40ef5cfb03bfac719d5f1c5ea770c4d1e2f44f84429a81ab622e50b2479970e3401ecd245d22b4bf1d18df37da9435621e2c470","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"d33a98424478fc31c356c03c5b63fe0f8f5530497e2d9a78a65c26d02f8f9f6b59","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:05 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"108.61.176.106","inbound_port":1776,"outbound_port":1776,"node_public_key":"031e9d4abe6de21333860641c3f586d1f4b229a5ce0a95e879a5100c129da06e87","signed_shared_secret":"205bf2eb9edd34e264fa2718f1d30efbf5dc6ad66d0366d7a8b21538a8badf2f1d4214dff4ada84b3cd8fe81045e3c1a1c459f038390c3ff54b6906ffd4e6fce9a","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"e2dbfe5e093cb445ae258e61368bcf815fee714d41f82d267246b26f57f04345e8","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:05 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"139.162.183.240","inbound_port":1776,"outbound_port":1776,"node_public_key":"03c86d5b8be4193691c02a800f68acba54ae6f4d5e0eface427c55babf33cea5cf","signed_shared_secret":"2022c13f1da058628a7644a368fed9228893b41316fe0108bbe47879985ad84a816035c069f2a831e94cc79b5166aa7944ec87e8e67842e9c2fb85a83cde220cc1","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"31adee49d91275cc63aa3a47b3a9e3c826baccca","fc_git_revision_unix_timestamp":1458656254,"platform":"linux","bitness":64,"node_id":"88374afef31c3939761badd74a7a797fd2ce97aff5354a410f32f39904ba1ff928","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:05 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"45.32.159.93","inbound_port":1776,"outbound_port":1776,"node_public_key":"036b06fe171588e07421ac67889cbcf4694119c16644aabb765107048b64c9c08f","signed_shared_secret":"1f6eac2d4e81b70bc9c71a50faf84f279176c08d5d3913fccadb91e701c6ac792c406554b29a4104108a40da87b5195d6abbd4dd8e10d272c141b21419af6427ed","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"b04994475ee8b7ff84f82f8b5ddd4ccab0bce8c081200d457af79c7b4e5893b1e6","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:05 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Connection reset by peer 
    {"message":"Connection reset by peer"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:05 p2p:message read_loop on_connection_closed ] Remote peer 51.15.42.228:50696 closed their connection to us			node.cpp:2993
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nConnection reset by peer \n    {\"message\":\"Connection reset by peer\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nConnection reset by peer \n    {\"message\":\"Connection reset by peer\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Connection reset by peer 
    {"message":"Connection reset by peer"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:05 p2p:message read_loop on_connection_closed ] Remote peer 45.77.136.107:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nConnection reset by peer \n    {\"message\":\"Connection reset by peer\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nConnection reset by peer \n    {\"message\":\"Connection reset by peer\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:message read_loop on_connection_reject ] Received a rejection from 192.121.166.162:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:05 p2p:message read_loop on_closing_connectio ] Peer 192.121.166.162:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:05 p2p:message read_loop on_connection_reject ] Received a rejection from 84.200.84.162:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:05 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:05 p2p:message read_loop on_connection_closed ] Remote peer 192.121.166.162:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:message read_loop on_closing_connectio ] Peer 84.200.84.162:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:05 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:05 p2p:message read_loop on_connection_closed ] Remote peer 84.200.84.162:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:message read_loop on_connection_reject ] Received a rejection from 148.251.80.54:4243 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:05   p2p:connect_to_task           connect_to ] established outbound connection to 188.241.58.128:1776			peer_connection.cpp:259
2017-11-08T07:49:05 p2p:message read_loop on_closing_connectio ] Peer 148.251.80.54:4243 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:05 p2p:message read_loop on_connection_reject ] Received a rejection from 94.130.15.169:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:05 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:05 p2p:message read_loop on_connection_closed ] Remote peer 148.251.80.54:4243 closed their connection to us			node.cpp:2993
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:message read_loop on_closing_connectio ] Peer 94.130.15.169:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:05 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:05 p2p:message read_loop on_connection_closed ] Remote peer 94.130.15.169:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:message read_loop on_connection_reject ] Received a rejection from 212.47.249.84:50696 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:05 p2p:message read_loop on_connection_reject ] Received a rejection from 108.61.176.106:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:05 p2p:message read_loop on_closing_connectio ] Peer 108.61.176.106:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:05 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:05 p2p:message read_loop on_connection_closed ] Remote peer 108.61.176.106:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:message read_loop on_closing_connectio ] Peer 212.47.249.84:50696 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:05 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:05 p2p:message read_loop on_connection_closed ] Remote peer 212.47.249.84:50696 closed their connection to us			node.cpp:2993
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:message read_loop on_connection_reject ] Received a rejection from 139.162.183.240:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:05 p2p:message read_loop on_closing_connectio ] Peer 139.162.183.240:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:05 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:05 p2p:message read_loop on_connection_closed ] Remote peer 139.162.183.240:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:05 p2p:message read_loop on_connection_reject ] Received a rejection from 45.32.159.93:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:message read_loop on_closing_connectio ] Peer 45.32.159.93:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:05 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:05 p2p:message read_loop on_connection_closed ] Remote peer 45.32.159.93:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:05 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:05"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:05 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"188.241.58.128","inbound_port":1776,"outbound_port":1776,"node_public_key":"0372b629ed171c26951061f7001116f003c0c4e552eb85982d203e73a5b73cd263","signed_shared_secret":"1f619e20a7ca4009a90cb7103f0d975ff300493afdb71d65ef42a6092515426bc95320f883ffab75fd17c50a3719a05990995ac3df8ef1055cad7844142fc12b9e","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"6351ffc166d5db8f0530bbf95da83e2830f4341a2353e27e18a2fd4b72ea43a2af","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:06   p2p:connect_to_task           connect_to ] established outbound connection to 45.79.174.179:1776			peer_connection.cpp:259
2017-11-08T07:49:06   p2p:connect_to_task           connect_to ] established outbound connection to 173.233.75.2:1776			peer_connection.cpp:259
2017-11-08T07:49:06 p2p:message read_loop on_connection_reject ] Received a rejection from 188.241.58.128:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:06 p2p:message read_loop on_closing_connectio ] Peer 188.241.58.128:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:06 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:06 p2p:message read_loop on_connection_closed ] Remote peer 188.241.58.128:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06   p2p:connect_to_task           connect_to ] established outbound connection to 192.151.158.106:1776			peer_connection.cpp:259
2017-11-08T07:49:06 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"45.79.174.179","inbound_port":1776,"outbound_port":1776,"node_public_key":"037782e5a273ecdd5fd15e3671e8d3747a30f325dacf411ecd2de6ac745e4263f3","signed_shared_secret":"1f4bdb92ddeb93482be408a14972a5ea2cdbe7164b5773c3cc0ed92bf9c67580933458d9e20510dcdafb357dabeabb03a64e4be25186665f56d863e4b44eb5cb81","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"039afe7f10a18ea106c1cef4c547d3f9af5075464cc685708db7b3cfbe24a3375c","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:06   p2p:connect_to_task           connect_to ] established outbound connection to 71.197.2.119:1776			peer_connection.cpp:259
2017-11-08T07:49:06   p2p:connect_to_task           connect_to ] established outbound connection to 209.105.239.13:1776			peer_connection.cpp:259
2017-11-08T07:49:06 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"173.233.75.2","inbound_port":1776,"outbound_port":1776,"node_public_key":"03ec672f71a78022a22e7ee7cf553d0f24370b35f8bcb12156b0dd98fc92bdb9b3","signed_shared_secret":"1f1352881caa3e95115779a8c0b51ff592d7ef74002c7e8ef493fe9c4fb8544c0e7c62f8ec3165244b055fd03a54fbbbd0a78609bd5452dda4d2f3a0371f74615a","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"81eb0294b8534aec1d18fbfe7b01c6d24287c3b04394f3f2402020bfd9d7f8db97","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:06 p2p:message read_loop on_connection_reject ] Received a rejection from 45.79.174.179:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:06 p2p:message read_loop on_closing_connectio ] Peer 45.79.174.179:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:06 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:06 p2p:message read_loop on_connection_closed ] Remote peer 45.79.174.179:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:06 p2p:send_queued_messages_task send_queued_messages ] Error sending message: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"error","file":"asio.cpp","line":38,"method":"operator()","hostname":"","thread_name":"asio","timestamp":"2017-11-08T07:49:06"},"format":"${message} ","data":{"message":"Bad file descriptor"}},{"context":{"level":"warn","file":"stcp_socket.cpp","line":159,"method":"writesome","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"","data":{"len":16}},{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":270,"method":"send_message","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"unable to send message","data":{}}]}.  Closing connection.			peer_connection.cpp:315
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"192.151.158.106","inbound_port":1776,"outbound_port":1776,"node_public_key":"03353fb691341ebbbf772750ef7a8e1e2092f9709e928f2ec9ac75bcaae783bee5","signed_shared_secret":"1f32ce4ac726db0294ec758d86b0de2702cff924a5eb4d073b5f290629efafa0d02bfbc6a88f7036663878ae787034ab58b7a85c017a1d90ee40e92fb7325c7f19","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"101a87ffbd5c8f050b60affe3aaae7946fa72527ed95b55b3e48c651e2d5ace331","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:06   p2p:connect_to_task           connect_to ] established outbound connection to 23.92.53.182:1776			peer_connection.cpp:259
2017-11-08T07:49:06   p2p:connect_to_task           connect_to ] established outbound connection to 128.199.143.47:2015			peer_connection.cpp:259
2017-11-08T07:49:06   p2p:connect_to_task           connect_to ] established outbound connection to 114.92.224.87:62015			peer_connection.cpp:259
2017-11-08T07:49:06 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"71.197.2.119","inbound_port":1776,"outbound_port":1776,"node_public_key":"02dac70e008bf71c1bdc2d1d7e0d50657bc63bf713650e2dd956a7638caf696e8e","signed_shared_secret":"205497fddf8d3c99c9700145c2b2c5239e23181fe58d1b5ae70077b56fe28c97fc6e0013e97628d32d078cc7a6ef20c0952c68a6a09137b54428b6131a73920c2c","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"bc8adccca266eef7cbfda38bb4ec2fc0cabde67fa3f88ffa902e54f4c5aa2351a1","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:06   p2p:connect_to_task           connect_to ] established outbound connection to 116.62.226.52:1776			peer_connection.cpp:259
2017-11-08T07:49:06 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"209.105.239.13","inbound_port":1776,"outbound_port":1776,"node_public_key":"03cc9a82119c50fb1639dc6c301aac3b7aa9d6a17bc83e3396f0846af926dad3ad","signed_shared_secret":"1f3b2d816400de62f2e3a23173d7b4ba3f8793b38da2e2b8279efa640e0c6f600a4402ee615f9b04673089b4e0a26bca6a0c01347cca9207b36730c871a1b75f54","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"bb2452b00da32a22d7322ae7aad9dd0e1f1707dc7c2abb1c6f1d806d3027c7bde1","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:06 p2p:message read_loop on_connection_reject ] Received a rejection from 173.233.75.2:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:06 p2p:message read_loop on_closing_connectio ] Peer 173.233.75.2:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:06 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:06 p2p:message read_loop on_connection_closed ] Remote peer 173.233.75.2:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06   p2p:connect_to_task           connect_to ] established outbound connection to 45.32.117.94:1776			peer_connection.cpp:259
2017-11-08T07:49:06 p2p:message read_loop on_connection_reject ] Received a rejection from 192.151.158.106:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:06 p2p:message read_loop on_closing_connectio ] Peer 192.151.158.106:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:06 p2p:send_queued_messages_task send_queued_messages ] Error sending message: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"error","file":"asio.cpp","line":38,"method":"operator()","hostname":"","thread_name":"asio","timestamp":"2017-11-08T07:49:06"},"format":"${message} ","data":{"message":"Bad file descriptor"}},{"context":{"level":"warn","file":"stcp_socket.cpp","line":159,"method":"writesome","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"","data":{"len":16}},{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":270,"method":"send_message","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"unable to send message","data":{}}]}.  Closing connection.			peer_connection.cpp:315
2017-11-08T07:49:06 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:06 p2p:message read_loop on_connection_closed ] Remote peer 192.151.158.106:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:message read_loop on_connection_reject ] Received a rejection from 71.197.2.119:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:06 p2p:message read_loop on_closing_connectio ] Peer 71.197.2.119:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:06 p2p:send_queued_messages_task send_queued_messages ] Error sending message: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"error","file":"asio.cpp","line":38,"method":"operator()","hostname":"","thread_name":"asio","timestamp":"2017-11-08T07:49:06"},"format":"${message} ","data":{"message":"Bad file descriptor"}},{"context":{"level":"warn","file":"stcp_socket.cpp","line":159,"method":"writesome","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"","data":{"len":16}},{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":270,"method":"send_message","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"unable to send message","data":{}}]}.  Closing connection.			peer_connection.cpp:315
2017-11-08T07:49:06 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:06 p2p:message read_loop on_connection_closed ] Remote peer 71.197.2.119:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"23.92.53.182","inbound_port":1776,"outbound_port":1776,"node_public_key":"025a4a45af3c3bfb39c7252a0a4b0a8dfbca381ff50591bdf21bfc0b0d9a0b10ec","signed_shared_secret":"1f569199027abee71e7674234f372cac3c25d10a75462d9433d7f22fc55ac256831f024e15ba8382e6211275940262e15c73cc882ef87779baa1df4d2359abb94b","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"a36906cc1afb77a2e1d442093743b892e3d2a17435c3ee697adc0d89de2d575bd2","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:06 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"128.199.143.47","inbound_port":2015,"outbound_port":2015,"node_public_key":"0321ca07bc4d670a0e51bcff8ab4ee67e2cdab9c3af3847ee13229b3bb9563083e","signed_shared_secret":"20271142596042fc9a45ed32cde851064cd1bb5060d9f1bf74700514fdf59767e357ffecc0ccf3a9117c94b4f7886637cab238ffea58315dfae027874660612b1e","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"30760a81eaaa4ed91f4f87fa49f161d56e0969c34bb5302c59253316ce0611358b","last_known_block_hash":"01329181c65837214e42dfb41b6f2480fba25260","last_known_block_number":20091265,"last_known_block_time":"1970-01-01T00:00:00"}}			node.cpp:1950
2017-11-08T07:49:06 p2p:message read_loop on_connection_reject ] Received a rejection from 209.105.239.13:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:06 p2p:message read_loop on_closing_connectio ] Peer 209.105.239.13:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:06 p2p:send_queued_messages_task send_queued_messages ] Error sending message: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"error","file":"asio.cpp","line":38,"method":"operator()","hostname":"","thread_name":"asio","timestamp":"2017-11-08T07:49:06"},"format":"${message} ","data":{"message":"Bad file descriptor"}},{"context":{"level":"warn","file":"stcp_socket.cpp","line":159,"method":"writesome","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"","data":{"len":16}},{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":270,"method":"send_message","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"unable to send message","data":{}}]}.  Closing connection.			peer_connection.cpp:315
2017-11-08T07:49:06 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:06 p2p:message read_loop on_connection_closed ] Remote peer 209.105.239.13:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"114.92.224.87","inbound_port":62015,"outbound_port":62015,"node_public_key":"035f2c5b80769d4bb720d92a5d1b504bdd7917f74418ef656ebc81ca2a4836ecd5","signed_shared_secret":"1f7175a3f36505fa9ec4da95148b49aec0abb59a44ad238cf592fe8c5b715f356266a692cfecbd1d5d94fa04fcb328f36eabd7bd4d91a583b97fe53ba512555176","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"31adee49d91275cc63aa3a47b3a9e3c826baccca","fc_git_revision_unix_timestamp":1458656254,"platform":"linux","bitness":64,"node_id":"fea4543c9d8d6ae261550fb1f2ad1c62414a1463a9e6fd898eff1790a31fc1d421","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:06 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"116.62.226.52","inbound_port":1776,"outbound_port":1776,"node_public_key":"0246fc2a8b5e215495a3f4542c88656f1ed83eee9719fb892c81ab0ef82329e11a","signed_shared_secret":"2077ff2f2e50a40bfb92ce0af69e38acc9878ccbed625526671434a4f81aaeb482076d97f3fe660f517418e136b88979e499738b746d47feecc5abd64614bf8b02","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"1e1542a88babd165d97b57c4944c2d0cefdb4a961d76785aa207f79829429f44c7","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:06 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"45.32.117.94","inbound_port":1776,"outbound_port":1776,"node_public_key":"031e9d4abe6de21333860641c3f586d1f4b229a5ce0a95e879a5100c129da06e87","signed_shared_secret":"1f754c3ad23fd92fdad416a89f4591a19927bc6d6aebe01a6f6bbb7cce951fdf0c2e9fbdef2576f3e5fa764cffd1aa44d7d338e93778605f65e8e35422307fea4f","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"ce98be626dc662a3ad56544b7687e09673b2d75ce56f603995b65ac4d714ba4075","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:06 p2p:message read_loop on_connection_reject ] Received a rejection from 23.92.53.182:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:06 p2p:message read_loop on_closing_connectio ] Peer 23.92.53.182:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:06 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:06 p2p:message read_loop on_connection_closed ] Remote peer 23.92.53.182:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:message read_loop on_connection_reject ] Received a rejection from 128.199.143.47:2015 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:06 p2p:message read_loop on_closing_connectio ] Peer 128.199.143.47:2015 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:06 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:06 p2p:message read_loop on_connection_closed ] Remote peer 128.199.143.47:2015 closed their connection to us			node.cpp:2993
2017-11-08T07:49:06 p2p:message read_loop on_connection_reject ] Received a rejection from 114.92.224.87:62015 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:06 p2p:message read_loop on_closing_connectio ] Peer 114.92.224.87:62015 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:06 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:06 p2p:message read_loop on_connection_closed ] Remote peer 114.92.224.87:62015 closed their connection to us			node.cpp:2993
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:message read_loop on_connection_reject ] Received a rejection from 116.62.226.52:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:06 p2p:message read_loop on_closing_connectio ] Peer 116.62.226.52:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:06 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:06 p2p:message read_loop on_connection_closed ] Remote peer 116.62.226.52:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:06 p2p:send_queued_messages_task send_queued_messages ] Error sending message: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"error","file":"asio.cpp","line":38,"method":"operator()","hostname":"","thread_name":"asio","timestamp":"2017-11-08T07:49:06"},"format":"${message} ","data":{"message":"Bad file descriptor"}},{"context":{"level":"warn","file":"stcp_socket.cpp","line":159,"method":"writesome","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"","data":{"len":16}},{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":270,"method":"send_message","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"unable to send message","data":{}}]}.  Closing connection.			peer_connection.cpp:315
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:message read_loop on_connection_reject ] Received a rejection from 45.32.117.94:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:06 p2p:message read_loop on_closing_connectio ] Peer 45.32.117.94:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:06 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:06 p2p:message read_loop on_connection_closed ] Remote peer 45.32.117.94:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06   p2p:connect_to_task           connect_to ] established outbound connection to 149.56.17.159:1776			peer_connection.cpp:259
2017-11-08T07:49:06 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"149.56.17.159","inbound_port":1776,"outbound_port":1776,"node_public_key":"0215ad94c7693d5879cbca07f310fc99f284e5d4997c97d388eac0fa7bb927f9c5","signed_shared_secret":"201a3c4f14b9faeaddcad7f397dcb31c7a70599537e19cdaa5b9e166db7a15a608342c20a2ed2384943c4b46c47f6d0a6fc62fd987040499c861241a14284bdb08","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"7bce08646556ed96b78ebdbe6176f4d3d774574deb6cbb5e9ea3690c8b5294b973","last_known_block_hash":"0149b3b7ab09631c41d758a17ab4e20baf38f6ab","last_known_block_number":21607351,"last_known_block_time":"2017-11-08T07:49:03"}}			node.cpp:1950
2017-11-08T07:49:06 p2p:message read_loop on_connection_reject ] Received a rejection from 149.56.17.159:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:06 p2p:message read_loop on_closing_connectio ] Peer 149.56.17.159:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:06 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:06 p2p:message read_loop on_connection_closed ] Remote peer 149.56.17.159:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:06 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:06"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:11 p2p:terminate_inactive_connections_loop terminate_inactive_c ] Forcibly disconnecting from handshaking peer 104.236.144.84:1777 due to inactivity of at least 5 seconds			node.cpp:1341
2017-11-08T07:49:11 p2p:terminate_inactive_connections_loop terminate_inactive_c ] Peer's negotiating status: connecting, bytes sent: 0, bytes received: 0			node.cpp:1345
2017-11-08T07:49:11 p2p:terminate_inactive_connections_loop terminate_inactive_c ] Forcibly disconnecting from handshaking peer 104.145.234.6:1777 due to inactivity of at least 5 seconds			node.cpp:1341
2017-11-08T07:49:11 p2p:terminate_inactive_connections_loop terminate_inactive_c ] Peer's negotiating status: connecting, bytes sent: 0, bytes received: 0			node.cpp:1345
2017-11-08T07:49:11   p2p:connect_to_task           connect_to ] fatal: error connecting to peer 104.236.144.84:1777: 0 exception: unspecified
Operation canceled 
    {"message":"Operation canceled"}
    asio  asio.cpp:60 error_handler			peer_connection.cpp:263
2017-11-08T07:49:11   p2p:connect_to_task           connect_to ] fatal: error connecting to peer 104.145.234.6:1777: 0 exception: unspecified
Operation canceled 
    {"message":"Operation canceled"}
    asio  asio.cpp:60 error_handler			peer_connection.cpp:263
2017-11-08T07:49:11 p2p:delayed_peer_deletion_task              destroy ] Unexpected exception from peer_connection's accept_or_connect_task : {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"error","file":"asio.cpp","line":60,"method":"error_handler","hostname":"","thread_name":"asio","timestamp":"2017-11-08T07:49:11"},"format":"${message} ","data":{"message":"Operation canceled"}}]}			peer_connection.cpp:166
2017-11-08T07:49:11 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:11 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:11 p2p:delayed_peer_deletion_task              destroy ] Unexpected exception from peer_connection's accept_or_connect_task : {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"error","file":"asio.cpp","line":60,"method":"error_handler","hostname":"","thread_name":"asio","timestamp":"2017-11-08T07:49:11"},"format":"${message} ","data":{"message":"Operation canceled"}}]}			peer_connection.cpp:166
2017-11-08T07:49:11 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:11 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35   p2p:connect_to_task           connect_to ] established outbound connection to 45.77.136.107:1776			peer_connection.cpp:259
2017-11-08T07:49:35   p2p:connect_to_task           connect_to ] established outbound connection to 51.15.42.228:50696			peer_connection.cpp:259
2017-11-08T07:49:35 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"51.15.42.228","inbound_port":50696,"outbound_port":50696,"node_public_key":"03b14cb5c7368d0230014b6f5b6a0228c2cee4113178403076471aff4c0cbd8f23","signed_shared_secret":"2052e250d5511ff5702efc0294e8e3f0beff7325fe82969c29eea9449c45210b04311cea191ab2c85531f0c1c1bd164b98e9354f92e1edb8294ad84153fb010018","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"43c0bd27292143ee8244fdef6fd1b6e1d9f12e546ef27cef8e174bb499470d37fb","last_known_block_hash":"0149b3c1760bb4c9e80681088369f131cb17efe6","last_known_block_number":21607361,"last_known_block_time":"2017-11-08T07:49:33"}}			node.cpp:1950
2017-11-08T07:49:35 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"45.77.136.107","inbound_port":1776,"outbound_port":1776,"node_public_key":"0234f748b1c02c54205cd87a327efaf7903d2ed8d85fbdcc63831d25a6e4ed2d2f","signed_shared_secret":"1f6273425f31b57a308758e4ec5c112d39fb98e9a1052f2329f09bef666fedbbe1307c7807f289a514a76a55febfc552c2f50e237ebb8790fe149a22451e7a5982","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"8d2c3f204e1552bcedbd687eb269a16a8c68cc8fce68f214d90e39af49e162b872","last_known_block_hash":"0149b3c1760bb4c9e80681088369f131cb17efe6","last_known_block_number":21607361,"last_known_block_time":"2017-11-08T07:49:33"}}			node.cpp:1950
2017-11-08T07:49:35 p2p:message read_loop on_connection_reject ] Received a rejection from 51.15.42.228:50696 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:35 p2p:message read_loop on_closing_connectio ] Peer 51.15.42.228:50696 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:35 p2p:message read_loop on_connection_reject ] Received a rejection from 45.77.136.107:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:35   p2p:connect_to_task           connect_to ] established outbound connection to 192.121.166.162:1776			peer_connection.cpp:259
2017-11-08T07:49:35   p2p:connect_to_task           connect_to ] established outbound connection to 84.200.84.162:1776			peer_connection.cpp:259
2017-11-08T07:49:35 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:35 p2p:message read_loop on_connection_closed ] Remote peer 51.15.42.228:50696 closed their connection to us			node.cpp:2993
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35   p2p:connect_to_task           connect_to ] established outbound connection to 94.130.15.169:1776			peer_connection.cpp:259
2017-11-08T07:49:35   p2p:connect_to_task           connect_to ] established outbound connection to 148.251.80.54:4243			peer_connection.cpp:259
2017-11-08T07:49:35 p2p:message read_loop on_closing_connectio ] Peer 45.77.136.107:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:35 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"192.121.166.162","inbound_port":1776,"outbound_port":1776,"node_public_key":"022d10653992817547534562c9adb7ab91dbeb078461fb59fb23a5eb95b758e56d","signed_shared_secret":"1f404990971f724faefaf755d58a51d02cfbcc846aecb817b9f0c83d05e1f0b4bf37a49c8eb41ba2a904ea65cac8dc6a0403dcfb6f950e80d23100989803576e97","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"91bcd57ec79bc75f9c9b8537408a4bfccbe53125fd754933701618cd6de8d8674a","last_known_block_hash":"0149b3c1760bb4c9e80681088369f131cb17efe6","last_known_block_number":21607361,"last_known_block_time":"2017-11-08T07:49:33"}}			node.cpp:1950
2017-11-08T07:49:35   p2p:connect_to_task           connect_to ] established outbound connection to 108.61.176.106:1776			peer_connection.cpp:259
2017-11-08T07:49:35   p2p:connect_to_task           connect_to ] established outbound connection to 212.47.249.84:50696			peer_connection.cpp:259
2017-11-08T07:49:35 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:35 p2p:message read_loop on_connection_closed ] Remote peer 45.77.136.107:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:35 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"84.200.84.162","inbound_port":1776,"outbound_port":1776,"node_public_key":"03ba3c1bc553eed45104d9ad950a9c9772c12c3e22d375081e59c17d2f5ce98e57","signed_shared_secret":"1f13c709768d8b87daaa1de8b63e64d91935710ea29d91333323df696885b0ddc1089135340312b8f364e9e6ef70e77026ca237df2b245973021ec83fb54f0824e","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"c3611922afc4388172f79e3d86361c1b253d79a8b00c4b21b296097f5449723e86","last_known_block_hash":"0149b3c1760bb4c9e80681088369f131cb17efe6","last_known_block_number":21607361,"last_known_block_time":"2017-11-08T07:49:33"}}			node.cpp:1950
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35   p2p:connect_to_task           connect_to ] established outbound connection to 139.162.183.240:1776			peer_connection.cpp:259
2017-11-08T07:49:35   p2p:connect_to_task           connect_to ] established outbound connection to 45.32.159.93:1776			peer_connection.cpp:259
2017-11-08T07:49:35 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"94.130.15.169","inbound_port":1776,"outbound_port":1776,"node_public_key":"023d064db50ca1abc9f785cc61bfa46e7f55c62e707ca31f4d0aa2d5607cb3e077","signed_shared_secret":"1f13373cfd3ee0b42df5952b9b1af118127cba3529f19daaaa0ebcc7d6c658edd029372cd6459b43b32f961dcfe4130f4ec145a53d006105bc0de846bcd2d494da","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"f5c566e21099c97d02e38e6f639befecc1acac7e4de3712c39cfaad40fc928c52d","last_known_block_hash":"0149b3c1760bb4c9e80681088369f131cb17efe6","last_known_block_number":21607361,"last_known_block_time":"2017-11-08T07:49:33"}}			node.cpp:1950
2017-11-08T07:49:35 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"148.251.80.54","inbound_port":4243,"outbound_port":4243,"node_public_key":"02144ea8cf3032bb24fdd3c2a69fc273e4df96984452e9b077334b207204a31448","signed_shared_secret":"1f30a2d76babb5b3726583ddbbee6425919832e70e1cda3bb4b3c454ef4a62ee71215f09b8a57ebfd6046f389c8e6fa51f0a72fdee60f3598293c00f2a1b707172","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"ca20da8ec268641e62f9264b4bcf2e9601b1a5b16eb6c8672a50c1845d57d8c840","last_known_block_hash":"0149b3c1760bb4c9e80681088369f131cb17efe6","last_known_block_number":21607361,"last_known_block_time":"2017-11-08T07:49:33"}}			node.cpp:1950
2017-11-08T07:49:35 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"108.61.176.106","inbound_port":1776,"outbound_port":1776,"node_public_key":"031e9d4abe6de21333860641c3f586d1f4b229a5ce0a95e879a5100c129da06e87","signed_shared_secret":"1f76d811cd9837d3fc71a0d3f907ee42459b43f6ec757ba378296a5f48e9fc65b400f424def06c3afa26b6af8381f0ba7a963b7206ab6137289de9b29e9e5d7af3","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"e2dbfe5e093cb445ae258e61368bcf815fee714d41f82d267246b26f57f04345e8","last_known_block_hash":"0149b3c1760bb4c9e80681088369f131cb17efe6","last_known_block_number":21607361,"last_known_block_time":"2017-11-08T07:49:33"}}			node.cpp:1950
2017-11-08T07:49:35 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"212.47.249.84","inbound_port":50696,"outbound_port":50696,"node_public_key":"034f2e5b12f51495da800c61e96dcb6e8450af051c22e0e1e9184164f59358ce98","signed_shared_secret":"203fa0d8caf0cd66cb95caed47ac57a4bc6b8fda8ce575ab98f52c83c997507cdf71ed9e398a8a9633f4a69e26dc4870e5394a0d8518d0572c1bd320a589d3996a","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"d33a98424478fc31c356c03c5b63fe0f8f5530497e2d9a78a65c26d02f8f9f6b59","last_known_block_hash":"0149b3c1760bb4c9e80681088369f131cb17efe6","last_known_block_number":21607361,"last_known_block_time":"2017-11-08T07:49:33"}}			node.cpp:1950
2017-11-08T07:49:35 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"139.162.183.240","inbound_port":1776,"outbound_port":1776,"node_public_key":"03c86d5b8be4193691c02a800f68acba54ae6f4d5e0eface427c55babf33cea5cf","signed_shared_secret":"200dc30c2bece6979979fa36143e39587c9d9dc5dddc11fbdef689901281e1b27f168fcc9a1eb2f5162f725691fec3d66d8234c151b4394cff42ef2320ada18b66","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"31adee49d91275cc63aa3a47b3a9e3c826baccca","fc_git_revision_unix_timestamp":1458656254,"platform":"linux","bitness":64,"node_id":"88374afef31c3939761badd74a7a797fd2ce97aff5354a410f32f39904ba1ff928","last_known_block_hash":"0149b3c1760bb4c9e80681088369f131cb17efe6","last_known_block_number":21607361,"last_known_block_time":"2017-11-08T07:49:33"}}			node.cpp:1950
2017-11-08T07:49:35 p2p:message read_loop     on_hello_message ] Received hello message from peer on a different chain: {"user_agent":"BitShares Reference Implementation","core_protocol_version":106,"inbound_address":"45.32.159.93","inbound_port":1776,"outbound_port":1776,"node_public_key":"036b06fe171588e07421ac67889cbcf4694119c16644aabb765107048b64c9c08f","signed_shared_secret":"200e55facd71742b7369e738a359240b60dc11412f862b8fdc968ba29355f89dc1113da2eeef87cc448085b4425ab0727c839e8fa2ca59ae709254a54572ef462b","chain_id":"4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8","user_data":{"fc_git_revision_sha":"cb627980a5ff5f65fe129414dd96d3c2bd51b095","fc_git_revision_unix_timestamp":1496617993,"platform":"linux","bitness":64,"node_id":"b04994475ee8b7ff84f82f8b5ddd4ccab0bce8c081200d457af79c7b4e5893b1e6","last_known_block_hash":"0149b3c1760bb4c9e80681088369f131cb17efe6","last_known_block_number":21607361,"last_known_block_time":"2017-11-08T07:49:33"}}			node.cpp:1950
2017-11-08T07:49:35 p2p:message read_loop on_connection_reject ] Received a rejection from 192.121.166.162:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:35 p2p:message read_loop on_connection_reject ] Received a rejection from 84.200.84.162:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:35 p2p:message read_loop on_closing_connectio ] Peer 192.121.166.162:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:35 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:35 p2p:message read_loop on_connection_closed ] Remote peer 192.121.166.162:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:35 p2p:message read_loop on_closing_connectio ] Peer 84.200.84.162:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:35 p2p:message read_loop on_connection_closed ] Remote peer 84.200.84.162:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:message read_loop on_connection_reject ] Received a rejection from 94.130.15.169:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:35 p2p:message read_loop on_closing_connectio ] Peer 94.130.15.169:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:35 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:35 p2p:message read_loop on_connection_closed ] Remote peer 94.130.15.169:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:35 p2p:message read_loop on_connection_reject ] Received a rejection from 148.251.80.54:4243 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:message read_loop on_closing_connectio ] Peer 148.251.80.54:4243 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:35 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:35 p2p:message read_loop on_connection_closed ] Remote peer 148.251.80.54:4243 closed their connection to us			node.cpp:2993
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:message read_loop on_connection_reject ] Received a rejection from 212.47.249.84:50696 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:35 p2p:message read_loop on_closing_connectio ] Peer 212.47.249.84:50696 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:35 p2p:message read_loop on_connection_reject ] Received a rejection from 108.61.176.106:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:35 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:35 p2p:message read_loop on_connection_closed ] Remote peer 212.47.249.84:50696 closed their connection to us			node.cpp:2993
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:message read_loop on_closing_connectio ] Peer 108.61.176.106:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:35 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:35 p2p:message read_loop on_connection_closed ] Remote peer 108.61.176.106:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:message read_loop on_connection_reject ] Received a rejection from 45.32.159.93:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:35 p2p:message read_loop on_connection_reject ] Received a rejection from 139.162.183.240:1776 in response to my "hello", reason: "You're on a different chain than I am.  I'm on 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 and you're on 30876b9228e993d950d565e2ca9e2e95f9426b3064830ab2f66ada9887a8395f"			node.cpp:2132
2017-11-08T07:49:35 p2p:message read_loop on_closing_connectio ] Peer 45.32.159.93:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:35 p2p:message read_loop on_closing_connectio ] Peer 139.162.183.240:1776 is disconnecting us because: You are on a different chain from me			node.cpp:2950
2017-11-08T07:49:35 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:35 p2p:message read_loop on_connection_closed ] Remote peer 45.32.159.93:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:message read_loop            read_loop ] disconnected 0 exception: unspecified
Bad file descriptor 
    {"message":"Bad file descriptor"}
    asio  asio.cpp:38 operator()

    {"len":16}
    p2p  stcp_socket.cpp:117 readsome			message_oriented_connection.cpp:205
2017-11-08T07:49:35 p2p:message read_loop on_connection_closed ] Remote peer 139.162.183.240:1776 closed their connection to us			node.cpp:2993
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:35 p2p:delayed_peer_deletion_task   destroy_connection ] Exception thrown while canceling message_oriented_connection's read_loop, ignoring: {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"warn","file":"message_oriented_connection.cpp","line":207,"method":"read_loop","hostname":"","thread_name":"p2p","timestamp":"2017-11-08T07:49:35"},"format":"disconnected: ${e}","data":{"e":"0 exception: unspecified\nBad file descriptor \n    {\"message\":\"Bad file descriptor\"}\n    asio  asio.cpp:38 operator()\n\n    {\"len\":16}\n    p2p  stcp_socket.cpp:117 readsome"}}]}			message_oriented_connection.cpp:299
2017-11-08T07:49:42       p2p:accept_loop          accept_loop ] 9 canceled_exception: Canceled

    {}
    p2p  thread_d.hpp:461 start_next_fiber
Unable to accept connection on socket.
    {}
    p2p  tcp_socket.cpp:280 accept			node.cpp:4278
2017-11-08T07:49:42       p2p:accept_loop          accept_loop ] 0: 0 			node.cpp:4278
2017-11-08T07:49:42       p2p:accept_loop   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:42       p2p:accept_loop   destroy_connection ] in destroy_connection() for 			message_oriented_connection.cpp:286
2017-11-08T07:49:42  p2p:delete node_impl           ~node_impl ] cleaning up node			node.cpp:836
2017-11-08T07:49:42  p2p:delete node_impl           ~node_impl ] close			node.cpp:855
2017-11-08T07:49:42  p2p:delete node_impl           ~node_impl ] done			node.cpp:862
